main.cpp
Both InfiniSim/main.cpp and SystemTask.cpp periodically called
`lv_task_handler()`. This introduces a race condition, which leads to a
segmentation fault in either the main or the SystemTasks call of
`lv_task_handler()`.
Now `main` only calls the `lv_task_handler()` if the `SystemTask` does
not (while the screen is turned off). We need this for the Simulator,
otherwise the "Screen is OFF" message won't appear, and the right mouse
button won't be recognized to wake up the simulated screen.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/3
=> main: fix segfault because of lv_task_handler() concurrently called

main.cpp
If the Alarm is set, then switch away from the Alarm Screen and turn off
display to get the "Screen is OFF" overlay. When the alarm rings the
Screen is switched to the Alarm Screen, which triggers the current
screen (for example the Clock/WatchFace) to issue an `lv_obj_clean()`
call. This call removes the `screen_off_bg` object, before the main
`refresh_sceen()` of the simulator can do it. Later the simulator tries
to remove the `screen_off_bg` object again, which is a double-free of
memory resulting in a segfault.
To prevent this segfault add a callback to the `screen_off_bg` callback
which informs the simulator, that the object has already been removed.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/8
=> main: fix double free of screen_off_bg lv_obj

CMakeLists.txt, main.cpp
The current usage used the system `png.h` header instead of the intended
submodule header. This may break if the system header isn't at
`libpng16/png.h`.
Fix the include header to get the genreated include files and the
`png.h` from the submodule as described in
https://github.com/glennrp/libpng/issues/342#issuecomment-864589614
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/19
=> Fix libpng submodule usage

sim/drivers/SpiNorFlash.h
`SpiNorFlash.h` is a C++ header, but the `Identification` struct is
created in a C style using `typedef struct`. Clang issues a warining
about this discrepancy:
```
In file included from /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/systemtask/SystemTask.cpp:13:
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:16:21: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct __attribute__((packed)) {
^
Identification
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:17:9: note: type is not C-compatible due to this default member initializer
uint8_t manufacturer = 0;
^~~~~~~~~~~~~~~~~~~~
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:20:9: …
```
=> SpiNorFlash: use C++ style struct in C++ only header

sim/components/fs/FS.cpp
Like in `FileOpen()` interpret filenames starting with `/` as paths
relative to the current working directory by removing the first `/` from
the path.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/23
=> FS: fix FS::Stat function by looking at local dir instead of `/`

.github/workflows/lv_sim.yml
We consider in CMake if we add the font subdir, but we didn't install
the `lv_font_conv` binary in https://github.com/InfiniTimeOrg/InfiniSim/pull/29
=> CI: install lv_font_conv binary

main.cpp
Need to loop the notification_idx after half the notification_messages
size since the change of splitting the subject and message body into two
strings.
=> Fix notification segfault

main.cpp, sim/displayapp/LittleVgl.cpp, sim/displayapp/LittleVgl.h
Move lvgl display init from main.cpp into LittleVgl.cpp to be closer to InfiniTime, where display initialization is also done in LitteVgl.cpp.
Enable the original FlushDisplay code to get the screen transition animations like on the real PineTime.
Also slow down the rendering, to actually be able to see the screen flushing.
For the Up and Down screen transitions implement the screen movement.
When moving Down, move the the whole screen content down, and then draw the new part of the new screen at the top of the display. Repeat until screen transition is finished.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/13
=> LittleVgl: implement screen transitions like on PineTime

CMakeLists.txt, README.md, gif-h/LICENSE, gif-h/README.md, gif-h/gif-h-demo.cpp, gif-h/gif.h, main.cpp
Press key `I` (shift+`i`) to start a screen capture creating a gif with the captured screen. Hit `I` again to stop the screen recording.
---
Add gif-h helper header only library
Copied from https://github.com/charlietangora/gif-h
https://github.com/charlietangora/gif-h/commit/3d2657b9ad40aac9fd6f75ad079335856e94d664
=> Add gif-h helper to create screen capture

CMakeLists.txt
Support both the current modified `date/includes` directory and the
`date` submodules `date/include` directory.
Once https://github.com/InfiniTimeOrg/InfiniTime/pull/1183 is merged
and the InfiniTime submodule is checked in also update the GitHub Action
and the AUR package.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/42
=> cmake: support date submodule include dir

README.md
Updated the README with a working node.js version needed to build the project. My original version v10.19.0 wasn't able to build the fonts with the font generation changes in InfiniTime v1.10. Node.js v12.22.9 was tested and working on two of my own machines.
=> Updated README with node.js version

CMakeLists.txt, main.cpp, sim/displayapp/LittleVgl.cpp
Support changes in InfiniTimeOrg/InfiniTime#1258
The file `lv_pinetime_theme.c` is renamed to `InfiniTimeTheme.cpp`.
Need to pick up that change in the simulator to compile with the new cpp
file if it exists.
Furthermore use the new `InfiniTimeTheme.h` header in simulator files.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/49
=> Support "Centralize most color definitions"

.github/workflows/lv_sim.yml, CMakeLists.txt, README.md, littlefs-do-main.cpp
Add helper to modify spi raw file, to make experimenting with it easier.
```sh
$ ./littlefs-do --help
Usage: littlefs-do <command> [options]
Commands:
-h, --help           show this help message for the selected command and exit
stat                 show information of specified file or directory
ls                   list available files in 'spiNorFlash.raw' file
mkdir                create directory
rmdir                remove directory
rm                   remove directory or file
cp                   copy files into or out of flash file
settings             list settings from 'settings.h'
```
In the process restructure the CMake file for less duplicate
includes/defines for both executables (`infinisim` and `littlefs-do`).
=> littlefs-do binary to work with spi raw file

littlefs-do-main.cpp
In https://github.com/InfiniTimeOrg/InfiniTime/pull/1261 the enums for Notification ON/OFF were renamed to On/Off and the additional entry `Sleep` was added.
Update `littlefs-do` to this change.
Thanks @kieranc for finding this issue
=> Update Notification::On/Off enum rename

CMakeLists.txt, README.md, external/miniz/CMakeLists.txt, external/miniz/ChangeLog.md, external/miniz/LICENSE, external/miniz/download-url.txt, external/miniz/examples/example1.c, external/miniz/examples/example2.c, external/miniz/examples/example3.c, external/miniz/examples/example4.c, external/miniz/examples/example5.c, external/miniz/examples/example6.c, external/miniz/miniz.c, external/miniz/miniz.h, external/miniz/readme.md, external/nlohmann_json/CMakeLists.txt, external/nlohmann_json/include/nlohmann/json.hpp, littlefs-do-main.cpp
Add a new command `littlefs-do res load resource.zip` which loads
resources from a zip file to the SPI raw file.
Below an example `resource.zip` is loaded:
```sh
$ ./littlefs-do res load infinitime-resources-1.10.0.zip --verbose
Calling FS::Init()
running 'res'
running 'res load'
loading resource file: "infinitime-resources-1.10.0.zip"
zip: num of files in zip: 8
copy file teko.bin                  from zip to SPI path '/teko.bin'
copy file lv_font_dots_40.bin       from zip to SPI path '/lv_font_dots_40.bin'
copy file 7segments_40.bin          from zip to SPI path '/7segments_40.bin'
copy file bebas.bin                 from zip to SPI path '/bebas.bin'
copy file 7segments_115.bin         from zip to SPI path '/7segments_115.bin'
copy file matrix.bin                from zip to SPI path …
```
=> littlefs-do: unzip in memory and copy listed resources to SPI raw file

main.cpp
No longer spam the memory usage constantly. This makes the output much more useful by allowing to observe each change in memory usage, since the values now no longer get pushed up and scroll out of view rapidly.
---
Print used memory (and change since last print) in addition to free memory.
Example output:
```
Mem: 4952 used (-248) 9384 free
Mem: 5960 used (+1008) 8376 free
Mem: 5992 used ( +32) 8344 free
Mem: 5720 used (-272) 8616 free
Mem: 5728 used (  +8) 8608 free
Mem: 5880 used (+152) 8456 free
Mem: 5728 used (-152) 8608 free
```
=> Print memory usage (p/P) only on change

README.md
This package is needed to run this command on Fedora:
```sh
cmake -S . -B build
```
=> Add zlib-devel package

main.cpp
Since #1324 (https://github.com/InfiniTimeOrg/InfiniTime/pull/1324) / #1024 (https://github.com/InfiniTimeOrg/InfiniTime/pull/1024) DisplayApp needs the FileSystem as parameter to the constructor.
=> DisplayApp now takes the filesystem as ctor arguments

.github/workflows/lv_sim.yml, CMakeLists.txt, README.md
The `BUILD_RESOURCES` option is also available in `InfiniTime`, but we don't want to require building the firmware to test `resource.zip` file generation.
=> Add option BUILD_RESOURCES=ON to build resources for sim

sim/components/battery/BatteryController.h
I implemented a [low battery warning](https://github.com/InfiniTimeOrg/InfiniTime/pull/1352) and this little change should fix the problem with the simulator build. It is just a dummy function that always reports enough battery since the whole BatteryController seems to do nothing.
=> Add support for low battery warning

main.cpp
This patch disables dithering since it causes artifacts within the generated gif files.
Before:
After:
=> Infinisim: GifExporter: Disable dithering

main.cpp
This has been moved to DisplayApp in InfiniTime, so there were two instances in InfiniSim.
Fixes scrolling direction issue.
https://github.com/InfiniTimeOrg/InfiniTime/commit/6f942e20ed5881e0b520f4c4f0f1fd2ffb4a3a2b
=> Remove LVGL instance in main

littlefs-do-main.cpp, main.cpp
This fixed the build errors for my [PR](https://github.com/InfiniTimeOrg/InfiniTime/pull/1339) at InfiniTime that introduces an enum for the watch faces. I guess both should be merged together because this one here would break with the current develop without the enum.
I get another error when building with resources enabled so I could not test that part.
The changes also look incomplete in that they do not touch all current watch faces.
=> Fix for enum watch faces

README.md, main.cpp
For me with vscode triggering a breakpoint during a mouse swipe event handler freezes all interaction with the IDE.
As a workaround (and a nice way to play `Twos.h` :D ) map the direction keys to the corresponding swipe events.
=> main: add swipe direction keys to make debugging easier

main.cpp, sim/displayapp/LittleVgl.cpp
Something must have changed, but now the `MONITOR_ZOOM` factor must be considered when calling `SDL_RenderReadPixels`. Always calling with a monitor width and height of 240 results in a segmentation fault in said function.
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/95
=> Handle MONITOR_ZOOM for screen transitions and captures

CMakeLists.txt
The new analog watch face implementation in InfiniTime draws the background programmatically instead of using a background picture. This branch removes this background picture from the files needed by cmake to build the project.
This PR must be merged after https://github.com/InfiniTimeOrg/InfiniTime/pull/1824.
=> Fix for the new analog watch face implementation in InfiniTime

CMakeLists.txt, sim/components/motion/MotionController.cpp, sim/components/motion/MotionController.h
Fixes the build since InfiniTimeOrg/InfiniTime#826 was merged.
=> raisewake: Fix for new raise to wake impl

.github/workflows/lv_sim.yml, .gitmodules, CMakeLists.txt, README.md, main.cpp
On rolling distros the usage of `libpng` submodule makes problems as the `zlib` system dependency of said module gets updated. Then the submodule regularly is too old to handle the updates `zlib` dependency.
Fix this maintenance churn by requiring `libpng` as system library as well. Then the distros package manager keeps those versions in sync.
This unfortunately requires users to install a new runtime/build dependency, but it still can be disabled with `-DWITH_PNG=OFF`.
=> Remove libpng submodule and require system lib

CMakeLists.txt, README.md
The current readme of the `lv_font_conv` the minimum node.js version is
v14+. Update our readme to mention that minimum version as well.
And in CMake issue a warning if the detected node version is less than `v14.0`
Fixes: https://github.com/InfiniTimeOrg/InfiniSim/issues/109
=> Node v14 required for lv_font_conv

.github/workflows/lv_sim.yml
Install new build dependency introduced with move to minimum python implementation of `lv_img_conv` node js script
https://github.com/InfiniTimeOrg/InfiniTime/pull/1863
=> CI: install python3-pil for lv_img_conv.py

CMakeLists.txt
InfiniTime is switching to C++20 in [this PR](https://github.com/InfiniTimeOrg/InfiniTime/pull/1894) so InfiniSim needs to follow that change.
=> Enable C++20 in CMake

CMakeLists.txt
I could not build the simulator because of [this](https://cmake.org/cmake/help/latest/policy/CMP0153.html#policy:CMP0153).
This PR updates the CMake file to the newer function.
=> Fix CMP0153 for newer CMake versions

CMakeLists.txt, README.md
Integrate the new infinitime_apps library and enable user applications selection using the CMake variable ENABLE_USERAPPS.
=> User application selection with CMake

README.md, main.cpp, sim/components/ble/SimpleWeatherService.cpp, sim/components/ble/SimpleWeatherService.h
Generates random weather and forecast data. Also adds a new simulation key handler for weather data:
- 'w' will generate new weather, cycling through the various conditions
- 'W' will clear the weather data
Needed to build the sim for the weather app in https://github.com/InfiniTimeOrg/InfiniTime/pull/1995
=> SimpleWeatherService: Generate random weather data

sim/drivers/SpiMaster.cpp, sim/drivers/SpiMaster.h
Companion for https://github.com/InfiniTimeOrg/InfiniTime/pull/2046
=> Fixes for PR 2046 (SPI transaction hooks)

README.md
Added to the README file the Ubuntu command to install the python3-pil package. 
It was necessary on Ubuntu for me to successfully build the software.
=> Update README with Ubuntu command to install python3-pil 

CMakeLists.txt, sim/components/ble/SimpleWeatherService.cpp, sim/components/ble/SimpleWeatherService.h, sim/nrf_assert.h, sim/portmacro_cmsis.h, sim/queue.cpp, sim/queue.h, sim/semphr.cpp, sim/semphr.h
Companion for https://github.com/InfiniTimeOrg/InfiniTime/pull/2041
=> Fixes for PR 2041 (Continuous time updates)

main.cpp, sim/components/brightness/BrightnessController.h, sim/drivers/SpiNorFlash.cpp, sim/drivers/SpiNorFlash.h, sim/nrfx/hal/nrf_gpio.cpp, sim/nrfx/hal/nrf_gpio.h, sim/portmacro_cmsis.h
This introduces the necessary changes to deal with the changes introduced by the recent always on display and SPI JEDEC ID related commits to InfiniTime
=> fixes for Always On Display and SPI flash ID

CMakeLists.txt, main.cpp
Support for https://github.com/InfiniTimeOrg/InfiniTime/pull/1367 which is a rebase/improvement
of https://github.com/InfiniTimeOrg/InfiniTime/pull/1333 by @ght
The PR adds saving and restoring alarm state to the SPI NOR flash. So
the AlarmController needs the FileSystem-controller to work.
To support both the current `main` branch and the "save-alarm-to-file"
PR pass the Filesystem controller conditionally, only if
`Controller::FS` is mentioned in the `AlarmController.h` file
=> Conditionally pass Controllers::FS to AlarmController to support save to file

CMakeLists.txt
For InfiniTime PR https://github.com/InfiniTimeOrg/InfiniTime/pull/2107 a new systemtask file is introduced `WakeLock.h` and `WakeLock.cpp`.
If available add those files to the build target to support the current `main` and the new `WakeLock` using redesign.
=> Support WakeLock.h for doNotGoToSleep Refactor

sim/queue.cpp, sim/queue.h
PR https://github.com/InfiniTimeOrg/InfiniTime/pull/2109 refactors the `SystemTask.h` state machine to prevent `GoingToSleep` race conditions (and similar state transistions).
In doing so the function `uxQueueMessagesWaiting()` from NRF SDK was used. Implement this newly used function.
=> sim/queue: support uxQueueMessagesWaiting for SysTask state refactor

sim/displayapp/LittleVgl.cpp, sim/displayapp/LittleVgl.h
Add function `LittleVgl::ClearTouchState` introduced with https://github.com/InfiniTimeOrg/InfiniTime/pull/2108
As it is a new function the change is compatible with current v1.14.0-dev state (`main` branch of InfiniTime)
=> sim: LittleVgl: add new function ClearTouchState for PR #2108

CMakeLists.txt
The current firmware 1.14.0 doesn't use QCBOR in its code. Remove this removed residual dependency.
=> cmake: remove unused QCBOR cmake code

.github/workflows/lv_sim.yml
Same as InfiniTime, InfiniSim should be updated to use the new GitHub Actions.
https://github.com/InfiniTimeOrg/InfiniTime/pull/2224
=> Update github actions to new version

sim/semphr.cpp
Fixes #172.
This race condition would make infinisim eventually crash with the message "Mutex released without being held" on my machine.
The function `xSemaphoreTake` waits for the semaphore to be available to take by  looping + sleeping until there is an element in the `pxQueue->queue`. Then it locks the `pxQueue->mutex` and checks the queuesize again. Since the first check is not done under the mutex, some other thread could remove the element from the queue before the mutex is locked. Then the second check in `xSemaphoreTake` will return false. The method `DateTimeController::CurrentDateTime()` uses a semaphore as a mutex to guard calls to `UpdateTime()`. But it (and the other methods from `DateTimeController`) do not check if `xSemaphoreTake` actually gave them the semaphore. They …
=> Fix crash caused by race condition in xSemaphoreTake

.gitignore
As request in https://github.com/InfiniTimeOrg/InfiniSim/pull/176#discussion_r2137575519 
This PR adds some autogenerated development files to the gitignore file
=> fix: ignore development files

.devcontainer/Dockerfile, README.md
Follow up to the issue described in https://github.com/InfiniTimeOrg/InfiniSim/pull/174#discussion_r2150883468. This prevents permission issues when using the dev container with podman, which is running rootless. Usage with docker then requires explicitly passing UID and GID of the local user. To produce artifacts owned by the local user. The command in the README is adjusted.
=> Make dev container compatible with podman
